### ISSUE TITLE
no values reported

### ISSUE THREAD

**Issue by cbrandlehner** [frncsdrk/node-red-contrib-linux-network-stats#2]
I tried your note but it is not working for me. I receive this feedback when triggering the node:

`{"payload":-1,"topic":"received_bytes_sec","_msgid":"5bb1c5f6.6c1e0c"}`

I assume, payload should be a value, not "-1".

**Comment by frncsdrk** [comment]
`payload` should indeed not be `-1`.
Could you please provide more information, so that I can try to reproduce?
- node-red version
- package version
- linux distro

**Comment by cbrandlehner** [comment]
Node-Red: 1.0.2
Node version: 10.16.3
npm: 6.12.0
node-red-contrib-linux-network-stats package version: 0.1.2
Linux distro: Raspbian GNU/Linux 10 (buster)
HW: Raspberry Pi 3

**Comment by frncsdrk** [comment]
Unfortunately I cannot reproduce the problem on other hardware than the Raspberry Pi. This seems to be an issue with the `systeminformation` package. The only advice I have for you at the moment is to open an issue upstream describing the problem.

**Comment by cbrandlehner** [comment]
OK, thanks for looking into this.
